name: Artifacts

on: [push]

jobs:
  windows:
    name: Windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        name: Cache
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-pc-windows-msvc

      - uses: actions/upload-artifact@v2
        name: Upload artifact
        with:
          name: fuzzysearch-cli-windows
          path: target/release/fuzzysearch-cli.exe
